version: "3.4"

services:

  riposte-server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    image: riposte/scope-riposte-integration-server
    environment:
      - SCOPE_DSN
      - SCOPE_SERVICE=riposte-server
      - GITHUB_REPOSITORY
      - GITHUB_SHA
      - GITHUB_WORKSPACE
      - GITHUB_RUN_ID
      - GITHUB_RUN_NUMBER
    volumes:
      - ~/.scope:/root/.scope
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5

  riposte-tests:
    build:
      context: .
      dockerfile: ./docker/tests/Dockerfile
    image: riposte/scope-riposte-integration-tests
    depends_on:
      - riposte-server
    links:
      - riposte-server
    volumes:
      - ~/.scope:/root/.scope
    environment:
      - CONCURRENT_REQUESTS=100
      - SCOPE_DSN
      - GITHUB_REPOSITORY
      - GITHUB_SHA
      - GITHUB_WORKSPACE
      - GITHUB_RUN_ID
      - GITHUB_RUN_NUMBER